config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/inspirations', to: 'pages#inspirations'
  get '/projects', to: 'pages#projects'
  get '/projects2', to: 'pages#projects2'

  resources :contacts, only: [:new, :create]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Nous avons bien reçu votre demande d'informations, nous vous répondrons dans les plus brefs délais"
      redirect_to new_contact_path
    else
      flash[:alert] = "Une erreur est survenue, réessayez."
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :descritpion)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def test
  end

  def test2
  end

  def projects
  end

  def projects2
  end

  def inspirations
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/contacts/new.html.erb
  <div class="contact-wrapper">
    <div class="container">
      <div class="row">

        <div class="col-xs-12 col-md-4 contact-card">
          <h4>Demandez</h4>
          <hr class="styline centred">
          <div class="form">
            <%= render 'shared/contact_form' %>
          </div>
        </div>

        <div class="col-xs-12 col-md-6 contact-card">
          <h4>Contactez</h4>
          <hr class="styline centred">
          <div class="icon-org">
            <div class="icon-org-2 shared">
              <div class="icons spaced">
                <p class ="infos-organized"><i class="fa fa-envelope-o" aria-hidden="true"></i></p>
                <p class ="infos-organized"><i class="fa fa-phone" aria-hidden="true"></i></p>
                <p class ="infos-organized"><i class="fa fa-map-marker" aria-hidden="true"></i></p>
              </div>
              <div class="infos spaced">
                <p class ="infos-organized">info@all-supplies.be</p>
                <p class ="infos-organized">+32 (0) 477 63 48 32</p>
                <p class="comp-address">Avenue Louis Lepoutre 74<br> 1050 Bruxelles</p>
              </div>
            </div>
            <div class="map shared">
              <iframe
              width="250"
              height="200"
              frameborder="0" style="border:0"
              src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDkZ-PfWP_i_8pR_YklJJgJbhLuoV9gHd0
              &q=Avenue+Louis+Lepoutre+74,Bruxelles+Belgique" allowfullscreen>
            </iframe>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>All Supplies</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <%= javascript_include_tag 'modernizr-custom' %>
</head>
<body>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= render 'shared/footer'%>
  <script type="text/javascript">
    $(document).ready(function() {
      $(".nav-item > [href]").each(function() {
        if (this.href == window.location.href) {
          $(this).addClass("navactive");
        }
      });
    });
  </script>
  <%= javascript_include_tag 'application' %>

</body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('../../assets/portrait.jpg');">
  <div class="banner-content">
    <h1>ARCHITECT & INTERIOR DESIGNER</h1>
    <hr class="styline">
    <p>Any work in architecture which does not express serenity is a Mistake.</p>
    <div class="banner-buttons">
      <a class="btn-banner btanner">PROJECTS</a>
      <a class="btn-banner-white btanner">CONTACT ME</a>
    </div>
  </div>
</div>

<div class="flex-grid">
  <div class="flexhare pictie" style="background-image: url('../../assets/pinterest interior archi 17-min.jpg');"></div>
  <div class="flexhare textie textie-white">
    <div style="text-align: center">
      <h4>FIRST PROJECT</h4>
      <div class="home-description">
        <p>Brussels, Belgium</p>
        <p>Periphery House, Full reconditionning</p>
        <p>Spring 2017</p>
      </div>
      <a href="#" class="btn-banner btanner">MORE</a>
    </div>
  </div>
  <div class="flexhare pictie" style="background-image: url('../../assets/pinterest interior archi 19-min.jpg');"></div>
</div>
<div class="flex-grid-2">
  <div class="flexhare pictie" style="background-image: url('../../assets/pinterest interior archi 21-min.jpg');"></div>
  <div class="flexhare pictie" style="background-image: url('../../assets/pinterest interior archi 13-min.jpg');"></div>
  <div class="flexhare pictie" style="background-image: url('../../assets/pinterest interior archi 6-min.jpg');"></div>
  <div class="flexhare textie textie-black">
    <div style="text-align: center;">
      <h4>SECOND PROJECT</h4>
      <div class="home-description">
        <p>Lasne, Belgium</p>
        <p>Factory, Reallocation</p> <!-- Reassignement? -->
        <p>Fall 2016</p>
      </div>
    </div>
  </div>
</div>

<div class="talk-section">
  <div style="text-align: center;">
    <h4 >LET'S TALK</h4>
    <div class="home-description">
      <p>If you're interested in my services and would like additionnal informations or have specific project questions, feel free to contact me.</p>
      <hr class="styline">
    </div>
      <%= link_to new_contact_path, class: "btanner black-btn" do %>
        CONTACT ME
      <%end%>

  </div>
</div>

app/views/pages/projects.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
  </div>
  <div class="row">
      <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
      </div>
    </div>
  <div class="row">
      <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= image_tag'crazy.jpg', class: "propic classicard" %>
      </div>
    </div>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= image_tag'crazy.jpg', class: "propic classicard" %>
    </div>
  </div>
</div>

app/views/pages/projects2.html.erb
  <div class="container">
    <div class="content">
      <div class="grid">
        <div class="grid__item" data-size="1280x853">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img02" />
          <div class="description description--grid">Assemblage</div>
          </a>
        </div>



        <div class="grid__item" data-size="958x1280">
          <a href="../../assets/pinterest interior archi 12-min.jpg" class="img-wrap"><img src="../../assets/pinterest interior archi 12-min.jpg" alt="img02" class="propic" />
            <div class="description description--grid">Demesne</div>
          </a>
        </div>




        <div class="grid__item" data-size="837x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img03" />
            <div class="description description--grid">Felicity</div>
          </a>
        </div>

        <div class="grid__item" data-size="1280x961">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img04" />
            <div class="description description--grid">Propinquity</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x1131">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img05" />
            <div class="description description--grid">Ephemeral</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x857">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img06" />
            <div class="description description--grid">Surreptitious</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img07" />
            <div class="description description--grid">Scintilla</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x853">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img08" />
            <div class="description description--grid">Vestigial</div>
          </a>
        </div>
        <div class="grid__item" data-size="865x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img09" />
            <div class="description description--grid">Zephyr</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img10" />
            <div class="description description--grid">Desideratum</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x850">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img11" />
            <div class="description description--grid">Quixotic</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x853">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img01" />
            <div class="description description--grid">Assemblage</div>
          </a>
        </div>
        <div class="grid__item" data-size="958x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img02" />
            <div class="description description--grid">Demesne</div>
          </a>
        </div>
        <div class="grid__item" data-size="837x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img03" />
            <div class="description description--grid">Felicity</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x961">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img04" />
            <div class="description description--grid">Propinquity</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x1131">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img05" />
            <div class="description description--grid">Ephemeral</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x857">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img06" />
            <div class="description description--grid">Surreptitious</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img07" />
            <div class="description description--grid">Scintilla</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x853">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img08" />
            <div class="description description--grid">Vestigial</div>
          </a>
        </div>
        <div class="grid__item" data-size="865x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img09" />
            <div class="description description--grid">Zephyr</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x1280">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img10" />
            <div class="description description--grid">Desideratum</div>
          </a>
        </div>
        <div class="grid__item" data-size="1280x850">
          <a href="../../assets/crazy.jpg" class="img-wrap"><img src="../../assets/crazy.jpg" alt="img11" />
            <div class="description description--grid">Quixotic</div>
          </a>
        </div>
      </div>
      <!-- /grid -->
      <div class="preview">
        <button class="action action--close"><i class="fa fa-times"></i><span class="text-hidden">Close</span></button>
        <div class="description description--preview"></div>
      </div>
      <!-- /preview -->
    </div>
    <!-- /content -->
  </div>

  <script src="../../assets/imagesloaded.pkgd.min.js"></script>
  <script src="../../assets/masonry.pkgd.min.js"></script>
  <script src="../../assets/classie.js"></script>
  <script src="../../assets/main.js"></script>
  <script>
    (function() {
      var support = { transitions: Modernizr.csstransitions },
        // transition end event name
        transEndEventNames = { 'WebkitTransition': 'webkitTransitionEnd', 'MozTransition': 'transitionend', 'OTransition': 'oTransitionEnd', 'msTransition': 'MSTransitionEnd', 'transition': 'transitionend' },
        transEndEventName = transEndEventNames[ Modernizr.prefixed( 'transition' ) ],
        onEndTransition = function( el, callback ) {
          var onEndCallbackFn = function( ev ) {
            if( support.transitions ) {
              if( ev.target != this ) return;
              this.removeEventListener( transEndEventName, onEndCallbackFn );
            }
            if( callback && typeof callback === 'function' ) { callback.call(this); }
          };
          if( support.transitions ) {
            el.addEventListener( transEndEventName, onEndCallbackFn );
          }
          else {
            onEndCallbackFn();
          }
        };

      new GridFx(document.querySelector('.grid'), {
        imgPosition : {
          x : 1,
          y : 0.75
        },
        pagemargin : 50,
        onOpenItem : function(instance, item) {
          instance.items.forEach(function(el) {
            if(item != el) {
              var delay = Math.floor(Math.random() * 150);
              el.style.WebkitTransition = 'opacity .4s ' + delay + 'ms cubic-bezier(.7,0,.3,1), -webkit-transform .4s ' + delay + 'ms cubic-bezier(.7,0,.3,1)';
              el.style.transition = 'opacity .4s ' + delay + 'ms cubic-bezier(.7,0,.3,1), transform .4s ' + delay + 'ms cubic-bezier(.7,0,.3,1)';

              el.style.WebkitTransform = 'translate3d(0,400px,0)';
              el.style.transform = 'translate3d(0,400px,0)';
              el.style.opacity = 0;
            }
          });
        },
        onCloseItem : function(instance, item) {
          instance.items.forEach(function(el) {
            if(item != el) {
              el.style.WebkitTransition = 'opacity .3s, -webkit-transform .3s';
              el.style.transition = 'opacity .3s, transform .3s';

              el.style.WebkitTransform = 'translate3d(0,0,0)';
              el.style.transform = 'translate3d(0,0,0)';
              el.style.opacity = 1;

              onEndTransition(el, function() {
                el.style.transition = 'none';
                el.style.WebkitTransform = 'none';
              });
            }
          });
        }
      });
    })();
  </script>

app/views/pages/test.html.erb
<div class="carousel-shell">
  <!-- CAROUSEL -->

  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active ">
        <%= image_tag 'hipster.jpg', class: "tales" %>
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <%= image_tag'modern.jpg', class: "tales" %>
        <div class="carousel-caption">
        </div>
      </div>
      <div class="item">
        <%= image_tag'crazy.jpg', class: "tales" %>
        <div class="carousel-caption">
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $.each( jQuery('.carousel .item'), function( i, val ) {
    $(this).css('background-image','url('+$(this).find('img').attr('src')+')').css('background-size','cover').find('img').css('visibility','hidden');
  });
</script>

app/views/shared/_contact_form.html.erb
<%= simple_form_for @contact do |f| %>
<%= f.error_notification %>
<%= f.input :email, placeholder: 'Email', label: false %>
<%= f.input :descritpion, placeholder: 'Quelle est votre question?', label: false, :input_html => {:rows => 5} %>
<%= f.button :submit, "Envoyez", class: 'btn-brand' %>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="up-foot">
  <div class="footer">
    <div class="navigation">
      <%= link_to root_path, class: "nav-foot-link nav-foot" do %>
        Home
      <%end%>
      <%= link_to projects_path, class: "nav-foot-link nav-foot" do %>
        Projets
      <%end%>
      <%= link_to inspirations_path, class: "nav-foot-link nav-foot" do %>
        Inspirations
      <%end%>
      <%= link_to new_contact_path, class: "nav-foot-link nav-foot" do %>
        Contact
      <%end%>
    </div>
    <div class="socials">
      <i class="fa fa-facebook  nav-foot-social nav-foot" aria-hidden="true"></i>
      <i class="fa fa-instagram nav-foot-social nav-foot" aria-hidden="true"></i>
      <i class="fa fa-linkedin  nav-foot-social nav-foot" aria-hidden="true"></i>
      <i class="fa fa-google-plus nav-foot-social nav-foot" aria-hidden="true"></i>
    </div>
  </div>
  <div class="jdi">
    This Website has been designed and developed by <i class="fa fa-copyright" aria-hidden="true"></i> JDi Agency
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="test-flex">
    <h1 class="home-header home-titles">ALL SUPPLIES</h1>
    <h2 class="home-subheader home-titles">Architectes d'Intérieur</h2>
    <hr class="styline">
  </div>

  <div class="nav-items">
    <div class="nav-item">
      <%= link_to root_path do %>
        Home
      <%end%>
      <hr class="styline">
    </div>
    <div class="nav-item">
      <%= link_to projects_path do %>
        Projets
      <%end%>
      <hr class="styline">
    </div>
    <div class="nav-item">
      <%= link_to inspirations_path do %>
        Inspirations
      <%end%>
      <hr class="styline">
    </div>
    <div class="nav-item">
      <%= link_to new_contact_path do %>
        Contact
      <%end%>
      <hr class="styline">
    </div>
  </div>
</div>